export interface NeedOption {
  id: string;
  label: string;
  /** the persona this need belongs to, offered as a "who should we help today?" pill */
  user: string;
  /**
   * capability pills offered for this need's 3 capability text fields (Phase 10's "examples"
   * chips) — deliberately spans the evolution spectrum (genesis/custom-built/product/commodity)
   * so the capabilities a visitor picks aren't all the same maturity, which matters once Phase 20
   * asks them to place each on the evolution axis.
   */
  capabilityOptions: string[];
}

/**
 * preset choices for Phase 10's "pick a user need" dropdown. Each option
 * carries its own capability pills so the form's suggested answers always
 * match the selected need — previously the capability fields' placeholder
 * text was hardcoded to the tea example ("Kettle") regardless of which need
 * was picked, which testers flagged as a content leak (see TODO.md).
 *
 * Several options can share a `user` — each user has multiple needs on offer, not just one — so
 * `user` is intentionally NOT unique across the catalog the way `id`, `label`, and the capability
 * options are (see `needCatalog.test.ts`).
 */
export const NEED_CATALOG: NeedOption[] = [
  {
    id: "hot-tea",
    label: "Hot Tea",
    user: "Commuter",
    capabilityOptions: [
      "Kettle",
      "Water",
      "Electricity",
      "Thermoelectric Mug",
      "Blacksmith's Kettle",
      "Induction Coil Ring",
      "Propane Camp Stove",
      "Instant Hot Water Dispenser",
      "Tea Bag",
      "Vending Machine",
    ],
  },
  {
    id: "reliable-wifi-on-the-train",
    label: "Reliable Wifi on the Train",
    user: "Commuter",
    capabilityOptions: [
      "Wifi Router",
      "Train Carriage",
      "Network Provider",
      "Laser Data Link",
      "Trackside Relay Antenna",
      "Low-Earth-Orbit Satellite Dish",
      "Personal Mobile Hotspot",
      "Onboard Wifi Access Point",
      "Cellular Data Plan",
      "Homemade Signal Booster",
    ],
  },
  {
    id: "a-parking-spot-downtown",
    label: "A Parking Spot Downtown",
    user: "Commuter",
    capabilityOptions: [
      "Parking Garage",
      "Payment Kiosk",
      "Security Camera",
      "Valet Drone",
      "Building Super's Driveway",
      "Automated Valet Elevator",
      "Sidewalk",
      "Parking App",
      "Parking Meter",
      "Curbside Hover Storage",
    ],
  },
  {
    id: "messaging-with-friends",
    label: "Messaging with Friends",
    user: "Teenager",
    capabilityOptions: [
      "Smartphone",
      "Messaging App",
      "Mobile Network",
      "Satellite Mesh Pager",
      "CB Radio Channel",
      "Ham Radio Repeater",
      "Home-Hosted Chat Server",
      "Video Call App",
      "Public Wifi Access",
      "SIM Card",
    ],
  },
  {
    id: "streaming-the-latest-show",
    label: "Streaming the Latest Show",
    user: "Teenager",
    capabilityOptions: [
      "Streaming App",
      "Wifi Connection",
      "Subscription Plan",
      "Neural Playback Headset",
      "Shared Family Login",
      "Retinal Projection Display",
      "Streaming Service Subscription",
      "Smart TV",
      "Broadband Internet",
      "HDMI Cable",
    ],
  },
  {
    id: "charging-their-phone-on-the-go",
    label: "Charging Their Phone on the Go",
    user: "Teenager",
    capabilityOptions: [
      "Portable Charger",
      "USB Cable",
      "Charging Port",
      "Solar-Weave Backpack",
      "Salvaged Laptop Battery",
      "Public Wireless Charging Grid",
      "Borrowed Car Charger",
      "Charging Locker",
      "Wall Outlet",
      "Battery Case",
    ],
  },
  {
    id: "fresh-grocery-delivery",
    label: "Fresh Grocery Delivery",
    user: "Home Cook",
    capabilityOptions: [
      "Delivery Driver",
      "Refrigerated Storage",
      "Online Ordering",
      "Delivery Drone",
      "Neighbor's Grocery Run",
      "Autonomous Sidewalk Rover",
      "Farmers Market Stand",
      "Meal Kit Subscription",
      "Delivery Van",
      "Cold Chain Packaging",
    ],
  },
  {
    id: "a-home-cooked-dinner-tonight",
    label: "A Home-Cooked Dinner Tonight",
    user: "Home Cook",
    capabilityOptions: [
      "Recipe App",
      "Stocked Pantry",
      "Stovetop",
      "Grandmother's Recipe Card",
      "AI Meal Planner",
      "Cooking Video Platform",
      "Backyard Vegetable Garden",
      "Grocery Store",
      "Smart Fridge Suggestion Engine",
      "Robotic Sous-Chef Arm",
    ],
  },
  {
    id: "a-week-of-meals-prepped",
    label: "A Week of Meals Prepped",
    user: "Home Cook",
    capabilityOptions: [
      "Batch Cooking Session",
      "Container Set",
      "Food Labels",
      "Slow Cooker",
      "Commercial Kitchen Rental",
      "Robotic Meal Assembly Line",
      "Repurposed Jam Jars",
      "Vacuum Sealer Machine",
      "Reused Takeout Containers",
      "Smart Container Freshness Sensor",
    ],
  },
  {
    id: "transport-to-the-airport",
    label: "Transport to the Airport",
    user: "Traveler",
    capabilityOptions: [
      "Driver",
      "Vehicle",
      "Road Network",
      "Air Taxi",
      "Neighbor's Carpool",
      "Autonomous Shuttle",
      "Off-Duty Taxi",
      "Rideshare App",
      "Taxi Stand",
      "Toll Road",
    ],
  },
  {
    id: "a-hotel-room-for-the-night",
    label: "A Hotel Room for the Night",
    user: "Traveler",
    capabilityOptions: [
      "Booking Platform",
      "Front Desk",
      "Room Key",
      "Capsule Hotel",
      "Host's Spare Room",
      "Automated Check-In Kiosk",
      "Couch-Surfing Network",
      "Hotel Loyalty App",
      "Housekeeping Service",
      "Air Conditioning Unit",
    ],
  },
  {
    id: "currency-exchanged-for-the-trip",
    label: "Currency Exchanged for the Trip",
    user: "Traveler",
    capabilityOptions: [
      "Exchange Kiosk",
      "Local Currency",
      "Exchange Rate",
      "Cross-Border Crypto Wallet",
      "Street Money Changer",
      "Biometric Payment Wristband",
      "Guesthouse Cash Exchange",
      "Travel Prepaid Card",
      "ATM",
      "Bank Wire Transfer",
    ],
  },
  {
    id: "documents-signed",
    label: "Documents Signed",
    user: "Contractor",
    capabilityOptions: [
      "E-Signature Tool",
      "Identity Verification",
      "Document Storage",
      "Blockchain Notarization",
      "Traveling Notary",
      "Biometric Signature Scanner",
      "Handwritten Ledger",
      "Digital Contract Platform",
      "Fax Machine",
      "Notary Stamp",
    ],
  },
  {
    id: "materials-delivered-to-the-job-site",
    label: "Materials Delivered to the Job Site",
    user: "Contractor",
    capabilityOptions: [
      "Supplier",
      "Delivery Truck",
      "Loading Dock",
      "Drone Freight",
      "Subcontractor's Pickup Truck",
      "Autonomous Cargo Rover",
      "Owner-Operator's Flatbed",
      "Freight Broker App",
      "Shipping Container",
      "Forklift",
    ],
  },
  {
    id: "a-permit-approved",
    label: "A Permit Approved",
    user: "Contractor",
    capabilityOptions: [
      "Permit Office",
      "Application Form",
      "Inspector",
      "Automated Permit Reviewer",
      "Government Clerk's Phone Number",
      "AI Zoning Compliance Checker",
      "Neighborhood Association Sign-Off",
      "Online Permit Portal",
      "Building Code Manual",
      "Filing Fee",
    ],
  },
  {
    id: "photos-displayed",
    label: "Photos Displayed",
    user: "Parent",
    capabilityOptions: [
      "Printer",
      "Photo Paper",
      "Ink",
      "Holographic Photo Booth",
      "Garage Darkroom",
      "Light-Field Camera",
      "Film Processing Lab",
      "Photo Printing Kiosk",
      "Photo Frame",
      "Digital Photo Album",
    ],
  },
  {
    id: "a-babysitter-for-date-night",
    label: "A Babysitter for Date Night",
    user: "Parent",
    capabilityOptions: [
      "Babysitting App",
      "Background Check",
      "Reference List",
      "Supervisor Robot",
      "Trusted Neighbor's Kid",
      "Nanny-Matching AI",
      "Grandparents",
      "Daycare Center",
      "Baby Monitor",
      "Emergency Contact List",
    ],
  },
  {
    id: "school-supplies-for-the-new-year",
    label: "School Supplies for the New Year",
    user: "Parent",
    capabilityOptions: [
      "Supply List",
      "Retail Store",
      "Backpack",
      "Replicator-Printed Supply Kit",
      "Parent Swap Meet",
      "Smart Backpack Tracker",
      "Teacher's Wish List",
      "School Supply Subscription Box",
      "Notebook Paper",
      "Pencil Case",
    ],
  },
];
